# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/roommate_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT Configuration Properties
app.jwt.secret=403f5728a64d1f2e30773d162a8a8e3230a103a8937072e9d28c895c24e6a0d4
app.jwt.expiration-ms=86400000

# Server Config
server.port=8081

# Logging
logging.level.org.springframework.security=INFO
